// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "App",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "App",
            targets: ["App"],
            bundleIdentifier: "com.swiftty.Legere",
            teamIdentifier: "B2TD54U4MA",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../Packages/legere-lib")
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                .product(name: "LegereLib", package: "legere-lib"),
                .product(name: "LegereDeps", package: "legere-lib"),
                .product(name: "LegereUI", package: "legere-lib")
            ]
        )
    ]
)